### ISSUE TITLE
Getting and using user data

### ISSUE THREAD

**Issue by nicktayl0r** [nicktayl0r/Gobbler#14]
Can log twitter api data but cannot show in the appropriate ejs file.

**Comment by jim-clark** [comment]
Is the twitter data being persisted in your db, or are you rendering as it comes back from the API.

Chances are, you need to JSON.stringify(<twitter data>) before passing it to the EJS view (you are passing it to the view - right?).

**Comment by nicktayl0r** [comment]
The goal is to persist the data in the db.

We are passing the data into the view. Ill try to stringfy my json and circle back.
